### ISSUE TITLE
Unable to set up integration - No module stream_unzip

### ISSUE THREAD

**Issue by PottiMc** [FL550/dwd_weather#157] opened 2024-10-21 12:26 UTC
HA is not loading the dwd integration with the following error log:

Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 14:20:44 (1 Vorkommnisse)
Zuletzt protokolliert: 14:20:44

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'stream_unzip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 12, in <module>
    from simple_dwd_weatherforecast import dwdforecast, dwdmap
  File "/usr/local/lib/python3.12/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 11, in <module>
    from stream_unzip import stream_unzip
ModuleNotFoundError: No module named 'stream_unzip'

I am using HAOS.

HA Core
2024.10.3
Supervisor
2024.10.2
Operating System
13.2
Frontend
20241002.3

**Comment by swa72** [comment] 2024-10-21 13:48
Same here ...

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 15:42:46 (1 occurrences)
Last logged: 15:42:46

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'stream_unzip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 12, in <module>
    from simple_dwd_weatherforecast import dwdforecast, dwdmap
  File "/usr/local/lib/python3.12/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 11, in <module>
    from stream_unzip import stream_unzip
ModuleNotFoundError: No module named 'stream_unzip'
```

**Comment by TiroHACS** [comment] 2024-10-21 14:23
same here after update core to 2024.10.3

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 14:46:17 (1 occurrences)
Last logged: 14:46:17

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'stream_unzip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 12, in <module>
    from simple_dwd_weatherforecast import dwdforecast, dwdmap
  File "/usr/local/lib/python3.12/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 11, in <module>
    from stream_unzip import stream_unzip
ModuleNotFoundError: No module named 'stream_unzip'

**Comment by pimisen** [comment] 2024-10-21 14:54
i second that. Came with the update of the core to 2024.10.3

**Comment by diplix** [comment] 2024-10-21 15:27
i run HA in docker with 2024.10.3 and see no such error. 
are you all using HAOS like PottiMc?

**Comment by TiroHACS** [comment] 2024-10-21 15:28
Yes, I'm running HAOS

**Comment by YamenSharaf** [comment] 2024-10-21 15:33
Same here. HAOS

**Comment by FL550** [comment] 2024-10-21 15:48
As nothing was changed from my side, I guess this might be an error in HAOS not pulling all the requirements correctly.

`stream_unzip` is a requirement of my underlying library for data retrieval and is there declared as a dependency. What I could try, is to define these also as a requirement for the main integration. However I am not sure if this fixes this error.

**Comment by TiroHACS** [comment] 2024-10-21 15:56
@FL550 Thanks, would be great if you could give it a try. If it is not working, I'll open a issue for HAOS Core as it has been working with 2024.10.2.

**Comment by swa72** [comment] 2024-10-21 16:55
If 2.1.18 is the pre-release, error is still present.

**Comment by FL550** [comment] 2024-10-21 17:33
Can someone check if the requirements are now at least installed during boot?

**Comment by FL550** [comment] 2024-10-21 17:41
See https://github.com/home-assistant/core/issues/128921 and https://github.com/home-assistant/core/issues/127966

**Comment by TiroHACS** [comment] 2024-10-21 21:04
@FL550 not sure whether this is what you are looking for, but it looks that stream_unzip is still "missing" with 2.1.18.

`Logger: homeassistant.setup
Source: setup.py:334
First occurred: 22:56:45 (1 occurrences)
Last logged: 22:56:45

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'stream_unzip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 12, in <module>
    from simple_dwd_weatherforecast import dwdforecast, dwdmap
  File "/usr/local/lib/python3.12/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 11, in <module>
    from stream_unzip import stream_unzip
ModuleNotFoundError: No module named 'stream_unzip'`

**Comment by pimisen** [comment] 2024-10-22 05:30
I just went back to Core 2024.10.2
Issue persists with the same error DWD Weather 2.1.18

**Comment by FL550** [comment] 2024-10-22 06:55
I'll post the issue which was filed on HA here for reference: https://github.com/home-assistant/core/issues/128921

**Comment by FL550** [comment] 2024-10-22 07:41
For now you can open a shell inside your container and install the modules by hand:

`python3 -m pip install simple_dwd_weatherforecast==2.1.10 markdownify==0.6.5 suntimes==1.1.2 lxml requests Pillow arrow stream-inflate==0.0.14 stream-unzip httpx`

**Comment by FL550** [comment] 2024-10-22 08:06
The problem also seems to be the same cause as in #155. 

It looks like HA has changed how dependencies are installed in 2024.10 and this has broken many custom integrations.

So basically this error only occurs to new installations or upgrades where the package cache was deleted. When you did an upgrade without deleting the HA config folder, everything should still work.

**Comment by TiroHACS** [comment] 2024-10-22 08:17
Thanks, @FL550 , but I don't think you've got any influence on HA config folder unless you upgrade the HAOS core manually step by step. Most people (including myself 😅 won't do that). So crossing fingers that it will be corrected with the core soonest. Thanks for your efforts.

**Comment by PottiMc** [comment] 2024-10-22 08:17
That's not true I think. I just clicked "Update" in my HA settings menu. Deleted nothing at all, especially not the config folder where all my stuff is.

**Comment by FL550** [comment] 2024-10-22 08:27
I'm also not sure on this, as I am running HA in a container on 2024.10.1 in my production environment and everything is working fine for now.

**Comment by PottiMc** [comment] 2024-10-22 08:30
It was working fine until 2024.10.2

**Comment by FL550** [comment] 2024-10-22 12:15
@Teonyr Thank you for providing the logs. This means that the packages have been installed previously which is correct behavior. Therefore we have to wait until this is fixed in HA itself. 

Please see #155 in the meantime as it might help here as well.

**Comment by diplix** [comment] 2024-10-22 13:58
problem turned up after a restrat in my HA, too. couldn’t fix it with rolling back to 2024.10.2 or eveb rolling back to 2024.9.3.
what fixed it for me was „rolling back“ one minor version of `stream-unzip` (in manifest.json):
```
{
  "domain": "dwd_weather",
  "version": "v2.1.18",
  "name": "Deutscher Wetterdienst (DWD)",
  "documentation": "https://github.com/FL550/dwd_weather",
  "issue_tracker": "https://github.com/FL550/dwd_weather/issues",
  "dependencies": [],
  "config_flow": true,
  "codeowners": [
    "@FL550"
  ],
  "requirements": [
    "simple_dwd_weatherforecast==2.1.10",
    "markdownify==0.6.5",
    "suntimes==1.1.2",
    "lxml",
    "requests",
    "Pillow",
    "arrow",
    "stream-inflate==0.0.14",
    "stream-unzip==0.0.95",
    "httpx"
  ],
  "iot_class": "cloud_polling"
}

```

**Comment by TiroHACS** [comment] 2024-10-22 14:05
Wow, thanks for sharing. How did you figure that out?🤔

**Comment by diplix** [comment] 2024-10-22 14:16
poking around … :)
since all other imports/dependencies worked fine, i figured that it must have something to do with `stream-unzip` and even before i saw the filed issue, noticed that the 0.0.96 release was from yesterday. so i pinned the version to 0.0.95 and it worked. actually i first ran this inside my docker:

`pip3 install stream-unzip==0.0.95 --upgrade`

seems to work with 2024.10.3, too — which is kind of strange.

**Comment by FL550** [comment] 2024-10-22 14:29
I'm not sure if this fixes this for everyone as I am guessing this is due to the package has veen already in cache. 

However I relaxed a new version which pins the version of stream_unzip to resolve it at least for the moment.

**Comment by LeonRein** [comment] 2024-10-22 14:45
I can confirm, that the problem is gone with release [v2.1.19](https://github.com/FL550/dwd_weather/releases/tag/v2.1.19).

**Comment by TiroHACS** [comment] 2024-10-22 14:49
Quick feedback also from me. Solved it here as well. Thanks!

**Comment by pimisen** [comment] 2024-10-22 16:24
Yeah. Thanks!

**Comment by FL550** [comment] 2024-10-22 18:07
It seems you are all long time users then 😉

**Comment by TiroHACS** [comment] 2024-10-22 20:21
@FL550 Well, that really doesn't matter. The community lives up based on different roles. You develop and open it to the community (many thanks for that 🙏), we provide feedback to help improving quality. This is how it works 🙂, isn't it? Everybody is doing the best possible.

**Comment by PottiMc** [comment] 2024-10-23 03:41
Thank you for your fast help. I am gonna close this now since the new release fixed it.

**Closed** 2024-10-23 03:41 UTC

**Comment by jkreimer** [comment] 2024-11-24 18:33
Workaround mentioned above worked for me to get DWD 2.1.24 running on HA 2024.11.03:

Executed within my docker container: `pip3 install stream-unzip==0.0.95 --upgrade`
